Akeneo\Pim\Enrichment\Component\Category\Model\Category:
    type: entity
    table: pim_catalog_category
    changeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: Akeneo\Tool\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository
    uniqueConstraints:
        pim_category_code_uc:
            columns:
                - code

    indexes:
        left_idx:
            columns:
                - lft
    fields:
        id:
            type: integer
            id: true
            generator:
                 strategy: AUTO
        code:
            type: string
            length: 100
            unique: true
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            options:
                default: CURRENT_TIMESTAMP
            gedmo:
                timestampable:
                    on: change
                    field:
                        - parent
        root:
            type: integer
        level:
            type: integer
            column: lvl
        left:
            type: integer
            column: lft
        right:
            type: integer
            column: rgt
    oneToMany:
        translations:
            targetEntity: Akeneo\Pim\Enrichment\Component\Category\Model\CategoryTranslationInterface
            mappedBy: foreignKey
            cascade:
                - persist
                - detach
            orphanRemoval: true
        channels:
            targetEntity: Akeneo\Channel\Component\Model\ChannelInterface
            mappedBy: category
        children:
            targetEntity: Akeneo\Pim\Enrichment\Component\Category\Model\CategoryInterface
            mappedBy: parent
            cascade:
                - persist
            orderBy:
                left: ASC
    manyToOne:
        parent:
            targetEntity: Akeneo\Pim\Enrichment\Component\Category\Model\CategoryInterface
            inversedBy: children
            joinColumns:
                parent_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    manyToMany:
        products:
            targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\ProductInterface
            mappedBy: categories
            fetch: EXTRA_LAZY
