framework:
    test: true
    session:
        storage_id: session.storage.mock_file
    cache:
        pools:
            cache.data:
                adapter: cache.adapter.array
                public: true
